{{- if .Values.rbac.create -}}
{{- $saName := default (printf "%s-compute" (include "streamarr.fullname" .)) .Values.rbac.serviceAccount.name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  labels:
    {{- include "streamarr.componentLabels" (dict "ctx" . "component" "compute") | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $saName }}
  labels:
    {{- include "streamarr.componentLabels" (dict "ctx" . "component" "compute") | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $saName }}
  labels:
    {{- include "streamarr.componentLabels" (dict "ctx" . "component" "compute") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $saName }}
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
