{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyrate.redisHost" . }}
  labels:
    {{- include "pyrate.componentLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
  selector:
    {{- include "pyrate.selectorLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pyrate.redisHost" . }}
  labels:
    {{- include "pyrate.componentLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
spec:
  serviceName: {{ include "pyrate.redisHost" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "pyrate.selectorLabels" (dict "ctx" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pyrate.componentLabels" (dict "ctx" . "component" "redis") | nindent 8 }}
    spec:
      {{- include "pyrate.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: redis
          image: {{ include "pyrate.image" (dict "ctx" . "img" .Values.redis.image) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if or .Values.redis.persistence.storageClass .Values.global.storageClass }}
        storageClassName: {{ default .Values.global.storageClass .Values.redis.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
  {{- end }}
{{- end -}}
