FROM node:22-alpine

WORKDIR /app

# Copy everything needed for install
COPY . .

RUN yarn install --frozen-lockfile

EXPOSE 3000

CMD ["npx", "quasar", "dev", "--hostname", "0.0.0.0", "--port", "3000"]
