"""empty message

Revision ID: 8ddc19538838
Revises: 
Create Date: 2026-01-17 22:26:42.244912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ddc19538838'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloader',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ssl', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_downloader_api_key'), 'downloader', ['api_key'], unique=False)
    op.create_index(op.f('ix_downloader_host'), 'downloader', ['host'], unique=False)
    op.create_index(op.f('ix_downloader_label'), 'downloader', ['label'], unique=False)
    op.create_index(op.f('ix_downloader_type'), 'downloader', ['type'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    op.create_table('indexer',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('ssl', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_indexer_api_key'), 'indexer', ['api_key'], unique=False)
    op.create_index(op.f('ix_indexer_host'), 'indexer', ['host'], unique=False)
    op.create_index(op.f('ix_indexer_label'), 'indexer', ['label'], unique=False)
    op.create_index(op.f('ix_indexer_type'), 'indexer', ['type'], unique=False)
    op.create_table('installed_plugins',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_installed_plugins_configured'), 'installed_plugins', ['configured'], unique=False)
    op.create_index(op.f('ix_installed_plugins_domain'), 'installed_plugins', ['domain'], unique=True)
    op.create_index(op.f('ix_installed_plugins_enabled'), 'installed_plugins', ['enabled'], unique=False)
    op.create_table('libraries',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('plugin_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_libraries_name'), 'libraries', ['name'], unique=False)
    op.create_index(op.f('ix_libraries_plugin_id'), 'libraries', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_libraries_type'), 'libraries', ['type'], unique=False)
    op.create_table('subscription_package',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allowed_libraries', sa.JSON(), nullable=False),
    sa.Column('max_quality_movies', sa.String(), nullable=True),
    sa.Column('max_quality_series', sa.String(), nullable=True),
    sa.Column('max_quality_music', sa.String(), nullable=True),
    sa.Column('max_concurrent_sessions', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('stripe_product_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('stripe_price_id')
    )
    op.create_index(op.f('ix_subscription_package_name'), 'subscription_package', ['name'], unique=False)
    op.create_table('user',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('oidc_sub', sa.String(), nullable=True),
    sa.Column('oidc_provider', sa.String(), nullable=True),
    sa.Column('preferred_username', sa.String(), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('groups', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('ui_language', sa.String(), nullable=True),
    sa.Column('audio_language', sa.String(), nullable=True),
    sa.Column('subtitle_language', sa.String(), nullable=True),
    sa.Column('quality_preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_oidc_provider'), 'user', ['oidc_provider'], unique=False)
    op.create_index(op.f('ix_user_oidc_sub'), 'user', ['oidc_sub'], unique=True)
    op.create_index(op.f('ix_user_preferred_username'), 'user', ['preferred_username'], unique=False)
    op.create_table('banners',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('banner_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dismissible', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_guid', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_guid'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_banners_banner_type'), 'banners', ['banner_type'], unique=False)
    op.create_index(op.f('ix_banners_created_at'), 'banners', ['created_at'], unique=False)
    op.create_index(op.f('ix_banners_created_by_guid'), 'banners', ['created_by_guid'], unique=False)
    op.create_index(op.f('ix_banners_dismissible'), 'banners', ['dismissible'], unique=False)
    op.create_index(op.f('ix_banners_end_date'), 'banners', ['end_date'], unique=False)
    op.create_index(op.f('ix_banners_is_active'), 'banners', ['is_active'], unique=False)
    op.create_index(op.f('ix_banners_start_date'), 'banners', ['start_date'], unique=False)
    op.create_index(op.f('ix_banners_title'), 'banners', ['title'], unique=False)
    op.create_table('device',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_ip_address', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('is_playing', sa.Boolean(), nullable=False),
    sa.Column('current_media_type', sa.String(), nullable=True),
    sa.Column('current_media_guid', sa.Uuid(), nullable=True),
    sa.Column('current_media_title', sa.String(), nullable=True),
    sa.Column('current_playback_position', sa.Integer(), nullable=False),
    sa.Column('current_playback_duration', sa.Integer(), nullable=False),
    sa.Column('playback_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_device_device_id'), 'device', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_user_id'), 'device', ['user_id'], unique=False)
    op.create_table('indexer_category',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('indexer_guid', sa.Uuid(), nullable=False),
    sa.Column('category_type', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['indexer_guid'], ['indexer.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_indexer_category_category_type'), 'indexer_category', ['category_type'], unique=False)
    op.create_index(op.f('ix_indexer_category_label'), 'indexer_category', ['label'], unique=False)
    op.create_table('invite',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.guid'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_invite_token'), 'invite', ['token'], unique=True)
    op.create_table('list',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('list_type', sa.Enum('SYSTEM', 'USER', name='listtype'), nullable=False),
    sa.Column('owner_guid', sa.Uuid(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'PUBLIC', name='listvisibility'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=False),
    sa.Column('update_source', sa.String(), nullable=True),
    sa.Column('last_auto_update', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('follow_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_guid'], ['user.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_list_is_active'), 'list', ['is_active'], unique=False)
    op.create_index(op.f('ix_list_list_type'), 'list', ['list_type'], unique=False)
    op.create_index(op.f('ix_list_name'), 'list', ['name'], unique=False)
    op.create_index(op.f('ix_list_owner_guid'), 'list', ['owner_guid'], unique=False)
    op.create_index(op.f('ix_list_visibility'), 'list', ['visibility'], unique=False)
    op.create_table('media_item',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.Enum('MOVIES', 'SHOWS', 'GAMES', 'MUSIC', 'BOOKS', 'AUDIOBOOKS', name='mediatype'), nullable=False),
    sa.Column('library_guid', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('availability_status', sa.Enum('UNKNOWN', 'AVAILABLE', 'DOWNLOADABLE', 'UNAVAILABLE', name='availabilitystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_searched_at', sa.DateTime(), nullable=True),
    sa.Column('last_metadata_updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_guid', sa.Uuid(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['library_guid'], ['libraries.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_guid'], ['media_item.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_media_item_availability_status'), 'media_item', ['availability_status'], unique=False)
    op.create_index(op.f('ix_media_item_library_guid'), 'media_item', ['library_guid'], unique=False)
    op.create_index(op.f('ix_media_item_media_type'), 'media_item', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_item_original_title'), 'media_item', ['original_title'], unique=False)
    op.create_index(op.f('ix_media_item_parent_guid'), 'media_item', ['parent_guid'], unique=False)
    op.create_index(op.f('ix_media_item_title'), 'media_item', ['title'], unique=False)
    op.create_table('notification',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.Enum('INFO', 'WARNING', 'ERROR', 'SUCCESS', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'READ', name='notificationstatus'), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('send_email', sa.Boolean(), nullable=False),
    sa.Column('email_template', sa.String(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('send_attempts', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_notification_status'), 'notification', ['status'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('user_subscription',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'EXPIRED', 'PENDING', 'FAILED', name='subscriptionstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('current_sessions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['subscription_package.guid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_table('watch_party',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('party_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_title', sa.String(), nullable=True),
    sa.Column('current_time', sa.Float(), nullable=False),
    sa.Column('is_playing', sa.Boolean(), nullable=False),
    sa.Column('playback_rate', sa.Float(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('allow_control', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_watch_party_is_active'), 'watch_party', ['is_active'], unique=False)
    op.create_index(op.f('ix_watch_party_media_id'), 'watch_party', ['media_id'], unique=False)
    op.create_index(op.f('ix_watch_party_media_type'), 'watch_party', ['media_type'], unique=False)
    op.create_index(op.f('ix_watch_party_owner_id'), 'watch_party', ['owner_id'], unique=False)
    op.create_index(op.f('ix_watch_party_party_code'), 'watch_party', ['party_code'], unique=True)
    op.create_table('favorite',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('media_item_guid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['media_item_guid'], ['media_item.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('user_id', 'media_item_guid', name='uq_favorite_user_media')
    )
    op.create_index(op.f('ix_favorite_media_item_guid'), 'favorite', ['media_item_guid'], unique=False)
    op.create_index(op.f('ix_favorite_user_id'), 'favorite', ['user_id'], unique=False)
    op.create_table('list_item',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('list_guid', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.Enum('MOVIE', 'SHOW', 'GAME', 'EPISODE', name='listitemtype'), nullable=False),
    sa.Column('item_guid', sa.Uuid(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('added_by_guid', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_guid'], ['user.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_guid'], ['list.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_list_item_added_by_guid'), 'list_item', ['added_by_guid'], unique=False)
    op.create_index(op.f('ix_list_item_item_guid'), 'list_item', ['item_guid'], unique=False)
    op.create_index(op.f('ix_list_item_item_type'), 'list_item', ['item_type'], unique=False)
    op.create_index(op.f('ix_list_item_list_guid'), 'list_item', ['list_guid'], unique=False)
    op.create_table('media_external_id',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('media_item_guid', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_item_guid'], ['media_item.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_media_external_id_external_id'), 'media_external_id', ['external_id'], unique=False)
    op.create_index(op.f('ix_media_external_id_media_item_guid'), 'media_external_id', ['media_item_guid'], unique=False)
    op.create_index(op.f('ix_media_external_id_provider'), 'media_external_id', ['provider'], unique=False)
    op.create_table('media_file',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('media_item_guid', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('probe_data', sa.String(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_item_guid'], ['media_item.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_media_file_file_path'), 'media_file', ['file_path'], unique=False)
    op.create_index(op.f('ix_media_file_media_item_guid'), 'media_file', ['media_item_guid'], unique=False)
    op.create_index(op.f('ix_media_file_quality'), 'media_file', ['quality'], unique=False)
    op.create_table('media_genre',
    sa.Column('media_item_guid', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_item_guid'], ['media_item.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_item_guid', 'genre_id')
    )
    op.create_table('media_release',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('media_item_guid', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('release_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('indexer_guid', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['indexer_guid'], ['indexer.guid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_item_guid'], ['media_item.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_media_release_indexer_guid'), 'media_release', ['indexer_guid'], unique=False)
    op.create_index(op.f('ix_media_release_media_item_guid'), 'media_release', ['media_item_guid'], unique=False)
    op.create_index(op.f('ix_media_release_quality'), 'media_release', ['quality'], unique=False)
    op.create_index(op.f('ix_media_release_score'), 'media_release', ['score'], unique=False)
    op.create_index(op.f('ix_media_release_title'), 'media_release', ['title'], unique=False)
    op.create_table('payment_history',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscription.guid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_table('scene_mapping',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tvdb_id', sa.Integer(), nullable=False),
    sa.Column('media_item_guid', sa.Uuid(), nullable=True),
    sa.Column('scene_title', sa.String(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('mapping_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['media_item_guid'], ['media_item.guid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_scene_mapping_mapping_type'), 'scene_mapping', ['mapping_type'], unique=False)
    op.create_index(op.f('ix_scene_mapping_media_item_guid'), 'scene_mapping', ['media_item_guid'], unique=False)
    op.create_index(op.f('ix_scene_mapping_scene_title'), 'scene_mapping', ['scene_title'], unique=False)
    op.create_index(op.f('ix_scene_mapping_source'), 'scene_mapping', ['source'], unique=False)
    op.create_index(op.f('ix_scene_mapping_tvdb_id'), 'scene_mapping', ['tvdb_id'], unique=False)
    op.create_index('ix_scene_mapping_tvdb_season', 'scene_mapping', ['tvdb_id', 'season_number'], unique=False)
    op.create_table('show_series_type',
    sa.Column('media_item_guid', sa.Uuid(), nullable=False),
    sa.Column('series_type', sa.String(), nullable=False),
    sa.Column('absolute_episode_offset', sa.Integer(), nullable=False),
    sa.Column('date_format', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['media_item_guid'], ['media_item.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_item_guid')
    )
    op.create_index(op.f('ix_show_series_type_series_type'), 'show_series_type', ['series_type'], unique=False)
    op.create_table('user_banner_dismissed',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('user_guid', sa.Uuid(), nullable=False),
    sa.Column('banner_guid', sa.Uuid(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['banner_guid'], ['banners.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_guid'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_user_banner_dismissed_banner_guid'), 'user_banner_dismissed', ['banner_guid'], unique=False)
    op.create_index(op.f('ix_user_banner_dismissed_dismissed_at'), 'user_banner_dismissed', ['dismissed_at'], unique=False)
    op.create_index(op.f('ix_user_banner_dismissed_user_guid'), 'user_banner_dismissed', ['user_guid'], unique=False)
    op.create_table('user_list_interaction',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_guid', sa.Uuid(), nullable=False),
    sa.Column('list_guid', sa.Uuid(), nullable=False),
    sa.Column('interaction_type', sa.Enum('LIKE', 'FOLLOW', 'BOOKMARK', name='userlistinteractiontype'), nullable=False),
    sa.ForeignKeyConstraint(['list_guid'], ['list.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_guid'], ['user.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('user_guid', 'list_guid', 'interaction_type', name='uq_user_list_interaction')
    )
    op.create_index(op.f('ix_user_list_interaction_interaction_type'), 'user_list_interaction', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_user_list_interaction_list_guid'), 'user_list_interaction', ['list_guid'], unique=False)
    op.create_index(op.f('ix_user_list_interaction_user_guid'), 'user_list_interaction', ['user_guid'], unique=False)
    op.create_table('user_session',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscription.guid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_user_session_session_token'), 'user_session', ['session_token'], unique=True)
    op.create_table('viewing_history',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_guid', sa.Uuid(), nullable=False),
    sa.Column('media_item_guid', sa.Uuid(), nullable=False),
    sa.Column('progress_seconds', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_watched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_item_guid'], ['media_item.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_guid'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_viewing_history_last_watched_at'), 'viewing_history', ['last_watched_at'], unique=False)
    op.create_index(op.f('ix_viewing_history_media_item_guid'), 'viewing_history', ['media_item_guid'], unique=False)
    op.create_index(op.f('ix_viewing_history_user_guid'), 'viewing_history', ['user_guid'], unique=False)
    op.create_table('watch_party_member',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=False),
    sa.Column('last_position', sa.Float(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['watch_party.guid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_watch_party_member_is_connected'), 'watch_party_member', ['is_connected'], unique=False)
    op.create_index(op.f('ix_watch_party_member_party_id'), 'watch_party_member', ['party_id'], unique=False)
    op.create_index(op.f('ix_watch_party_member_user_id'), 'watch_party_member', ['user_id'], unique=False)
    op.create_table('media_release_link',
    sa.Column('guid', sa.Uuid(), nullable=False),
    sa.Column('media_release_guid', sa.Uuid(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_release_guid'], ['media_release.guid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_media_release_link_link_type'), 'media_release_link', ['link_type'], unique=False)
    op.create_index(op.f('ix_media_release_link_media_release_guid'), 'media_release_link', ['media_release_guid'], unique=False)
    op.create_table('download',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('downloader_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('media_release_link_guid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['downloader_id'], ['downloader.guid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_release_link_guid'], ['media_release_link.guid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('guid')
    )
    op.create_index(op.f('ix_download_downloader_id'), 'download', ['downloader_id'], unique=False)
    op.create_index(op.f('ix_download_external_id'), 'download', ['external_id'], unique=False)
    op.create_index(op.f('ix_download_media_release_link_guid'), 'download', ['media_release_link_guid'], unique=False)
    op.create_index(op.f('ix_download_status'), 'download', ['status'], unique=False)
    op.create_index(op.f('ix_download_title'), 'download', ['title'], unique=False)
    op.create_index(op.f('ix_download_type'), 'download', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_type'), table_name='download')
    op.drop_index(op.f('ix_download_title'), table_name='download')
    op.drop_index(op.f('ix_download_status'), table_name='download')
    op.drop_index(op.f('ix_download_media_release_link_guid'), table_name='download')
    op.drop_index(op.f('ix_download_external_id'), table_name='download')
    op.drop_index(op.f('ix_download_downloader_id'), table_name='download')
    op.drop_table('download')
    op.drop_index(op.f('ix_media_release_link_media_release_guid'), table_name='media_release_link')
    op.drop_index(op.f('ix_media_release_link_link_type'), table_name='media_release_link')
    op.drop_table('media_release_link')
    op.drop_index(op.f('ix_watch_party_member_user_id'), table_name='watch_party_member')
    op.drop_index(op.f('ix_watch_party_member_party_id'), table_name='watch_party_member')
    op.drop_index(op.f('ix_watch_party_member_is_connected'), table_name='watch_party_member')
    op.drop_table('watch_party_member')
    op.drop_index(op.f('ix_viewing_history_user_guid'), table_name='viewing_history')
    op.drop_index(op.f('ix_viewing_history_media_item_guid'), table_name='viewing_history')
    op.drop_index(op.f('ix_viewing_history_last_watched_at'), table_name='viewing_history')
    op.drop_table('viewing_history')
    op.drop_index(op.f('ix_user_session_session_token'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_user_list_interaction_user_guid'), table_name='user_list_interaction')
    op.drop_index(op.f('ix_user_list_interaction_list_guid'), table_name='user_list_interaction')
    op.drop_index(op.f('ix_user_list_interaction_interaction_type'), table_name='user_list_interaction')
    op.drop_table('user_list_interaction')
    op.drop_index(op.f('ix_user_banner_dismissed_user_guid'), table_name='user_banner_dismissed')
    op.drop_index(op.f('ix_user_banner_dismissed_dismissed_at'), table_name='user_banner_dismissed')
    op.drop_index(op.f('ix_user_banner_dismissed_banner_guid'), table_name='user_banner_dismissed')
    op.drop_table('user_banner_dismissed')
    op.drop_index(op.f('ix_show_series_type_series_type'), table_name='show_series_type')
    op.drop_table('show_series_type')
    op.drop_index('ix_scene_mapping_tvdb_season', table_name='scene_mapping')
    op.drop_index(op.f('ix_scene_mapping_tvdb_id'), table_name='scene_mapping')
    op.drop_index(op.f('ix_scene_mapping_source'), table_name='scene_mapping')
    op.drop_index(op.f('ix_scene_mapping_scene_title'), table_name='scene_mapping')
    op.drop_index(op.f('ix_scene_mapping_media_item_guid'), table_name='scene_mapping')
    op.drop_index(op.f('ix_scene_mapping_mapping_type'), table_name='scene_mapping')
    op.drop_table('scene_mapping')
    op.drop_table('payment_history')
    op.drop_index(op.f('ix_media_release_title'), table_name='media_release')
    op.drop_index(op.f('ix_media_release_score'), table_name='media_release')
    op.drop_index(op.f('ix_media_release_quality'), table_name='media_release')
    op.drop_index(op.f('ix_media_release_media_item_guid'), table_name='media_release')
    op.drop_index(op.f('ix_media_release_indexer_guid'), table_name='media_release')
    op.drop_table('media_release')
    op.drop_table('media_genre')
    op.drop_index(op.f('ix_media_file_quality'), table_name='media_file')
    op.drop_index(op.f('ix_media_file_media_item_guid'), table_name='media_file')
    op.drop_index(op.f('ix_media_file_file_path'), table_name='media_file')
    op.drop_table('media_file')
    op.drop_index(op.f('ix_media_external_id_provider'), table_name='media_external_id')
    op.drop_index(op.f('ix_media_external_id_media_item_guid'), table_name='media_external_id')
    op.drop_index(op.f('ix_media_external_id_external_id'), table_name='media_external_id')
    op.drop_table('media_external_id')
    op.drop_index(op.f('ix_list_item_list_guid'), table_name='list_item')
    op.drop_index(op.f('ix_list_item_item_type'), table_name='list_item')
    op.drop_index(op.f('ix_list_item_item_guid'), table_name='list_item')
    op.drop_index(op.f('ix_list_item_added_by_guid'), table_name='list_item')
    op.drop_table('list_item')
    op.drop_index(op.f('ix_favorite_user_id'), table_name='favorite')
    op.drop_index(op.f('ix_favorite_media_item_guid'), table_name='favorite')
    op.drop_table('favorite')
    op.drop_index(op.f('ix_watch_party_party_code'), table_name='watch_party')
    op.drop_index(op.f('ix_watch_party_owner_id'), table_name='watch_party')
    op.drop_index(op.f('ix_watch_party_media_type'), table_name='watch_party')
    op.drop_index(op.f('ix_watch_party_media_id'), table_name='watch_party')
    op.drop_index(op.f('ix_watch_party_is_active'), table_name='watch_party')
    op.drop_table('watch_party')
    op.drop_table('user_subscription')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_status'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_media_item_title'), table_name='media_item')
    op.drop_index(op.f('ix_media_item_parent_guid'), table_name='media_item')
    op.drop_index(op.f('ix_media_item_original_title'), table_name='media_item')
    op.drop_index(op.f('ix_media_item_media_type'), table_name='media_item')
    op.drop_index(op.f('ix_media_item_library_guid'), table_name='media_item')
    op.drop_index(op.f('ix_media_item_availability_status'), table_name='media_item')
    op.drop_table('media_item')
    op.drop_index(op.f('ix_list_visibility'), table_name='list')
    op.drop_index(op.f('ix_list_owner_guid'), table_name='list')
    op.drop_index(op.f('ix_list_name'), table_name='list')
    op.drop_index(op.f('ix_list_list_type'), table_name='list')
    op.drop_index(op.f('ix_list_is_active'), table_name='list')
    op.drop_table('list')
    op.drop_index(op.f('ix_invite_token'), table_name='invite')
    op.drop_table('invite')
    op.drop_index(op.f('ix_indexer_category_label'), table_name='indexer_category')
    op.drop_index(op.f('ix_indexer_category_category_type'), table_name='indexer_category')
    op.drop_table('indexer_category')
    op.drop_index(op.f('ix_device_user_id'), table_name='device')
    op.drop_index(op.f('ix_device_device_id'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_banners_title'), table_name='banners')
    op.drop_index(op.f('ix_banners_start_date'), table_name='banners')
    op.drop_index(op.f('ix_banners_is_active'), table_name='banners')
    op.drop_index(op.f('ix_banners_end_date'), table_name='banners')
    op.drop_index(op.f('ix_banners_dismissible'), table_name='banners')
    op.drop_index(op.f('ix_banners_created_by_guid'), table_name='banners')
    op.drop_index(op.f('ix_banners_created_at'), table_name='banners')
    op.drop_index(op.f('ix_banners_banner_type'), table_name='banners')
    op.drop_table('banners')
    op.drop_index(op.f('ix_user_preferred_username'), table_name='user')
    op.drop_index(op.f('ix_user_oidc_sub'), table_name='user')
    op.drop_index(op.f('ix_user_oidc_provider'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_subscription_package_name'), table_name='subscription_package')
    op.drop_table('subscription_package')
    op.drop_index(op.f('ix_libraries_type'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_plugin_id'), table_name='libraries')
    op.drop_index(op.f('ix_libraries_name'), table_name='libraries')
    op.drop_table('libraries')
    op.drop_index(op.f('ix_installed_plugins_enabled'), table_name='installed_plugins')
    op.drop_index(op.f('ix_installed_plugins_domain'), table_name='installed_plugins')
    op.drop_index(op.f('ix_installed_plugins_configured'), table_name='installed_plugins')
    op.drop_table('installed_plugins')
    op.drop_index(op.f('ix_indexer_type'), table_name='indexer')
    op.drop_index(op.f('ix_indexer_label'), table_name='indexer')
    op.drop_index(op.f('ix_indexer_host'), table_name='indexer')
    op.drop_index(op.f('ix_indexer_api_key'), table_name='indexer')
    op.drop_table('indexer')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_downloader_type'), table_name='downloader')
    op.drop_index(op.f('ix_downloader_label'), table_name='downloader')
    op.drop_index(op.f('ix_downloader_host'), table_name='downloader')
    op.drop_index(op.f('ix_downloader_api_key'), table_name='downloader')
    op.drop_table('downloader')
    # ### end Alembic commands ###
