[package]
name = "streamarr"
version = "2026.2.1"
description = "A streaming media center."
authors = ["Sebastian Lübke <streamarr@luebke.dev>"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "streamarr_media_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
